TicariOtomasyon/TicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanID { get; set; }

        [Column(TypeName = "nvarchar")]
        [StringLength(30)]
        public string DepartmanAdi { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

TicariOtomasyon/TicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    [Authorize(Roles = "A,B")]
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkle()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            d.Durum = true;
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanGetir(int id)
        {
            var dept = c.Departmans.Find(id);
            return View("DepartmanGetir", dept);
        }
        public ActionResult DepartmanGuncelle(Departman d)
        {
            var dept1 = c.Departmans.Find(d.DepartmanID);
            dept1.DepartmanAdi = d.DepartmanAdi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();
            var dpt_adi = c.Departmans.Where(x => x.DepartmanID == id).Select(y => y.DepartmanAdi).FirstOrDefault();
            ViewBag.d_adi = dpt_adi;
            return View(degerler);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var per = c.Personels.Where(x => x.PersonelID == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            var dpt1_adi = c.Personels.Where(x => x.PersonelID == id).Select(y => y.Departmanid).FirstOrDefault();
            var dep_ad = c.Departmans.Where(x => x.DepartmanID == dpt1_adi).Select(y => y.DepartmanAdi).FirstOrDefault();


            ViewBag.p_adi = per;
            ViewBag.d_adi = dep_ad;
            return View(degerler);
        }
    }
}

TicariOtomasyon/TicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using TicariOtomasyon.Models.Siniflar;
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.0/jquery.fancybox.min.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.0/jquery.fancybox.min.js"></script>
<br />
<h2>Departman Detay</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Departman adı : @ViewBag.d_adi</li>
</ol>
<br />
<h5>Personeller</h5>
<table id="tbl_departman_detay" class="table table-striped">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Ad Soyad</th>
            <th>Görsel</th>
            <th>Satışlar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
        <tr>
            @*<td>@x.PersonelID</td>*@

            <td>@x.PersonelAd @x.PersonelSoyad</td>


            @*<td>@x.PersonelGorsel</td>*@<!--görsellere bak düzenlenecek var mı-->
            <td><a data-fancybox="gallery" target="_blank" class="btn btn-dark" href="@x.PersonelGorsel">Resim</a></td><!--Burası fotoğraf popup açma kodu-->

            <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-info">Satışlar</a></td>
        </tr>
    }

</table>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl_departman_detay').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model TicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
} 
<br />
<h2>Departman Ekle</h2>
<br />
<form class="form-group" method="post">

    <p>Departman adı giriniz</p>

    @Html.TextBoxFor(x => x.DepartmanAdi, new { @class = "form-control" })

    <br />
    <button class="btn btn-success">Kaydet</button>
</form>

TicariOtomasyon/TicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model TicariOtomasyon.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Güncelle</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        <p>Kategori adı</p>
        @Html.TextBoxFor(x => x.DepartmanAdi, new { @class = "form-control" })
        @Html.HiddenFor(x => x.DepartmanID)
    </div>
    <br />
    <button class="btn btn-success">Güncelle</button>
}

TicariOtomasyon/TicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel adı : @ViewBag.p_adi <br /> Departman : @ViewBag.d_adi</li>
</ol>
<br />
<table id="tbl_departman_personel_satis" class="table table-striped">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Ürün</th>
            <th>Cari</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Yazdır</th>
        </tr>
    </thead>
    @foreach (var a in Model)
    {
        <tr>

            @*<td>@a.SatisID</td>*@

            <td>@a.Urun.UrunAdi</td>

            <td>@a.Cariler.CariAd @a.Cariler.CariSoyad</td>

            <td>@a.Fiyat</td>

            <td>@a.Adet</td>

            <td>@a.ToplamTutar</td>

            <td>@Convert.ToDateTime(a.Tarih).ToString("dd/MM/yyyy")</td>

            <td><a href="#" class="btn btn-primary">Yazdır</a></td>

        </tr>
    }
</table>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl_departman_personel_satis').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Departman/Index.cshtml
@using TicariOtomasyon.Models.Siniflar;
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table id="departman" class="table table-striped" style="margin-top:20px">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Departman Adı</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Detay</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>

            @*<td>@k.DepartmanID</td>*@

            <td>@k.DepartmanAdi</td>

            @*<td><a href="/Departman/DepartmanSil/@k.DepartmanID" class="btn btn-danger">Sil</a></td>*@
            <td>
                @Html.ActionLink("Sil", "DepartmanSil", new { id = k.DepartmanID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istediğinizden emin misiniz?')" })
            </td>

            <td><a href="/Departman/DepartmanGetir/@k.DepartmanID" class="btn btn-warning">Güncelle</a></td>

            <td><a href="/Departman/DepartmanDetay/@k.DepartmanID" class="btn btn-info">Detay</a></td>

        </tr>
    }
</table>
<span>
    <a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>
</span>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#departman').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>