TicariOtomasyon/TicariOtomasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    [Authorize(Roles ="A,B")]
    public class CariController : Controller
    {
        // GET: Cari
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Carilers.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniCari()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniCari(Cariler cari)
        {
            cari.Durum = true;
            c.Carilers.Add(cari);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariSil(int id)
        {
            var carsil = c.Carilers.Find(id);
            carsil.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariGetir(int id)
        {
            var cari = c.Carilers.Find(id);
            return View("CariGetir",cari);
        }
        public ActionResult CariGuncelle(Cariler cr)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var cari = c.Carilers.Find(cr.CariID);
            cari.CariAd = cr.CariAd;
            cari.CariSoyad = cr.CariSoyad;
            cari.CariSehir = cr.CariSehir;
            cari.CariMail = cr.CariMail;
            cari.CariAdres = cr.CariAdres;
            cari.CariTelefon = cr.CariTelefon;
            c.SaveChanges(); 
            return RedirectToAction("Index");

        }
        public ActionResult MusteriSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            var cr = c.Carilers.Where(x => x.CariID == id).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.cari = cr;
            return View(degerler);
        }
    }
}

TicariOtomasyon/TicariOtomasyon/Views/Cari/CariGetir.cshtml
@model TicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Cari Güncelle</h2>
<br />
@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.CariID)
    <p>Ad</p>
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
    <br />

    <p>Soyad</p>
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:red" })
    <br />

    <p>Şehir</p>
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />

    <p>Mail</p>
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMail, "", new { @style = "color:red" })

    <br />

    <p>Telefon</p>
    @Html.TextBoxFor(x => x.CariTelefon, new { @class = "form-control",maxlength = "10",placeholder="554321456"})
    @Html.ValidationMessageFor(x => x.CariTelefon, "", new { @style = "color:red" })

    <br />

    <p>Adres</p>
    @Html.TextBoxFor(x => x.CariAdres, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAdres, "", new { @style = "color:red" })
    <br />

    <button class="btn btn-success">Güncelle</button>
</div>
}

TicariOtomasyon/TicariOtomasyon/Views/Cari/Index.cshtml
@using TicariOtomasyon.Models.Siniflar;
@model List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table id="tbl_cari" class="table table-striped">
    <thead>
        <tr>
            
            @*<th>#</th>*@
            
            <th>Ad</th>
            
            <th>Soyad</th>
            
            <th>Şehir</th>
            
            <th>Mail</th>

            <th>Telefon</th>

            <th>Adres</th>
            
            <th>Sil</th>
            
            <th>Güncelle</th>
            
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
        <tr>
            @*<td>@x.CariID</td>*@

            <td>@x.CariAd</td>

            <td>@x.CariSoyad</td>

            <td>@x.CariSehir</td>

            <td>@x.CariMail</td>
            
            <td>@x.CariTelefon</td>
            
            <td>@x.CariAdres</td>

            @*<td><a href="/Cari/CariSil/@x.CariID" class="btn btn-danger">Sil</a></td>*@
            <td>@Html.ActionLink("Sil", "CariSil", new { id = x.CariID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istediğinizden emin misiniz?')" })</td>

            <td><a href="/Cari/CariGetir/@x.CariID" class="btn btn-warning">Güncelle</a></td>

            <td><a href="/Cari/MusteriSatis/@x.CariID" class="btn btn-info">Satışlar</a></td>
        </tr>
    }
</table>
<a href="/Cari/YeniCari" class="btn btn-primary">Cari Ekle</a>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl_cari').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Cari/MusteriSatis.cshtml
@using TicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Müşteri Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari adı : @ViewBag.cari</li>
</ol>
<br />
<table id="tbl_musteri_satis" class="table table-striped">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Ürün</th>
            <th>Personel</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Yazdır</th>
        </tr>
    </thead>
    @foreach (var a in Model)
    {
        <tr>

            @*<td>@a.SatisID</td>*@

            <td>@a.Urun.UrunAdi</td>

            <td>@a.Personel.PersonelAd @a.Personel.PersonelSoyad</td>

            <td>@a.Fiyat</td>

            <td>@a.Adet</td>

            <td>@a.ToplamTutar</td>

            <td>@Convert.ToDateTime(@a.Tarih).ToString("dd/MM/yyyy")</td>

            <td><a href="#" class="btn btn-primary">Yazdır</a></td>

        </tr>
    }
</table>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl_musteri_satis').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Cari/YeniCari.cshtml
@model TicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "YeniCari";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Cari</h2>
<br />
<form class="form-group" method="post">

    <p>Adı</p>

    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })

    <br />
    <p>Soyadı</p>
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })

    <br />
    <p>Şehir</p>
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })

    <br />
    <p>Mail</p>
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })

    <br />
    <p>Telefon</p>
    @Html.TextBoxFor(x => x.CariTelefon, new { @class = "form-control", maxlength = "10", placeholder = "554321456" })

    <br />
    <p>Adres</p>
    @Html.TextBoxFor(x => x.CariAdres, new { @class = "form-control" })

    <br />
    <button class="btn btn-success">Kaydet</button>
</form>