TicariOtomasyon/TicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyon.Models.Siniflar;

namespace TicariOtomasyon.Controllers
{
    [Authorize(Roles = "A,B")]
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var liste = c.Faturalars.ToList();
            return View(liste);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir",fatura);
        }
        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var faturaa = c.Faturalars.Find(f.FaturaID);
            faturaa.FaturaSeriNo = f.FaturaSeriNo;
            faturaa.FaturaSiraNo = f.FaturaSiraNo;
            faturaa.FaturaSaat = f.FaturaSaat;
            faturaa.FaturaTarih = f.FaturaTarih;
            faturaa.TeslimAlan = f.TeslimAlan;
            faturaa.TeslimEden = f.TeslimEden;
            faturaa.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var degerler = c.FaturaKalems.Where(x => x.Faturaid == id).ToList();

            ViewBag.id1 = id;
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKalem(int id,FaturaKalem fk)
        {
            fk.Faturaid = id;
            c.FaturaKalems.Add(fk);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TicariOtomasyon/TicariOtomasyon/Views/Fatura/FaturaDetay.cshtml
@using TicariOtomasyon.Models.Siniflar;
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.0/jquery.fancybox.min.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.0/jquery.fancybox.min.js"></script>
<br />
<h2>Fatura Detayları</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Fatura Kalemleri</li> 
</ol>
<br />
<table id="tbl_departman_detay" class="table table-striped">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Açıklama</th>
            <th>Miktar</th>
            <th>Birim Fiyat</th>
            <th>Tutar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
<tr>
    @*<td>@x.FaturaKalemID</td>*@

    <td>@x.Aciklama</td>

    <td>@x.Miktar</td>

    <td>@x.BirimFiyat</td>

    <td>@x.Tutar</td>

    @*<td>@x.PersonelGorsel</td><!--görsellere bak düzenlenecek var mı-->
        <td><a data-fancybox="gallery" target="_blank" class="btn btn-dark" href="@x.PersonelGorsel">Resim</a></td><!--Burası fotoğraf popup açma kodu-->

        <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-info">Satışlar</a></td>*@
</tr>
    }

</table>

<a href="/Fatura/YeniKalem/@ViewBag.id1" class="btn btn-primary">Yeni giriş</a>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl_departman_detay').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Fatura/FaturaEkle.cshtml
@model TicariOtomasyon.Models.Siniflar.Faturalar
@{
    ViewBag.Title = "FaturaEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Fatura Ekle</h2>
<br />
<form class="form-group" method="post">
    <p>Seri No</p>
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })

    <br />

    <p>Sıra No</p>
    @Html.TextBoxFor(x => x.FaturaSiraNo, new { @class = "form-control" })

    <br />

    <p>Tarih</p>
    @Html.TextBoxFor(x => x.FaturaTarih, new { @class = "form-control", @type = "date", required = "required" })<!--Burası tarih--><!--Burası tarih-->

    <br />

    <p>Saat</p>
    @Html.TextBoxFor(x => x.FaturaSaat, new { @class = "form-control", @type = "time" })

    <br />

    <p>Vergi Dairesi</p>
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })

    <br />

    <p>Teslim eden</p>
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })

    <br />

    <p>Teslim alan</p>
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })

    <br />

    <p>Toplam</p>
    @Html.TextBoxFor(x => x.Toplam, new { @class = "form-control" })

    <br />

    <button class="btn btn-success">Kaydet</button>

</form>
<!--ürünlere fancybox eklenecek-->

TicariOtomasyon/TicariOtomasyon/Views/Fatura/FaturaGetir.cshtml
@model TicariOtomasyon.Models.Siniflar.Faturalar
@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Fatura Güncelle</h2>
<br />
@using (Html.BeginForm("FaturaGuncelle", "Fatura", FormMethod.Post))
{
    <p>Seri No</p>
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })

    <br />

    <p>Sıra No</p>
    @Html.TextBoxFor(x => x.FaturaSiraNo, new { @class = "form-control" })

    <br />

    <p>Tarih</p>
    @Html.TextBoxFor(x => x.FaturaTarih, new { @class = "form-control", @type = "date", required = "required" })<!--Burası tarih--><!--Burası tarih-->

    <br />

    <p>Saat</p>
    @Html.TextBoxFor(x => x.FaturaSaat, new { @class = "form-control", @type = "time" })

    <br />

    <p>Vergi Dairesi</p>
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })

    <br />

    <p>Teslim eden</p>
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })

    <br />

    <p>Teslim alan</p>
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })

    <br />

    @*<p>Toplam</p>
        @Html.TextBoxFor(x => x.Toplam, new { @class = "form-control" })*@

    <br />

    <button class="btn btn-success">Güncelle</button>
    @Html.HiddenFor(x => x.FaturaID)
}
<script>
    $("#date1").datetimepicker({
        format: 'yyyy-mm-dd'
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Fatura/Index.cshtml
@using TicariOtomasyon.Models.Siniflar;
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table id="faturalar" class="table table-striped" style="margin-top:20px">
    <thead>
        <tr>
            @*<th>#</th>*@
            <th>Seri-Sıra No</th>
            <th>Vergi dairesi</th>
            <th>Tarih</th>
            <th>Saat</th>
            <th>Teslim eden</th>
            <th>Teslim alan</th>
            <th>Toplam</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
<tr>

    @*<td>@k.FaturaID</td>*@

    <td>@k.FaturaSeriNo @k.FaturaSiraNo</td>

    <td>@k.VergiDairesi</td>

    <td>@Convert.ToDateTime(@k.FaturaTarih).ToString("dd/MM/yyyy")</td>

    <td>@k.FaturaSaat</td>

    <td>@k.TeslimEden</td>

    <td>@k.TeslimAlan</td>

    <td>@k.Toplam</td>

    @*<td><a href="/Departman/DepartmanSil/@k.DepartmanID" class="btn btn-danger">Sil</a></td>*@
    <td>
        @Html.ActionLink("Sil", "FaturaSil", new { id = k.FaturaID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istediğinizden emin misiniz?')" })
    </td>

    <td><a href="/Fatura/FaturaGetir/@k.FaturaID" class="btn btn-warning">Güncelle</a></td>

    <td><a href="/Fatura/FaturaDetay/@k.FaturaID" class="btn btn-info">Detay</a></td>

</tr>
    }
</table>
<span>
    <a href="/Fatura/FaturaEkle" class="btn btn-primary">Fatura Ekle</a>
</span>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#faturalar').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

TicariOtomasyon/TicariOtomasyon/Views/Fatura/YeniKalem.cshtml
@model TicariOtomasyon.Models.Siniflar.FaturaKalem
@{
    ViewBag.Title = "YeniKalem";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Giriş</h2>
<br />
<form class="form-group" method="post">
    <p>Açıklama</p>
    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })<!--Burada otomatik olarak ÜRÜN çekme işlemi yapılacak-->

    <br />

    <p>Miktar</p>
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })<!--Miktar max aşım olmayacak-->

    <br />

    <p>Birim Fiyat</p>
    @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })<!--otomatik olacak-->

    <br />

    <p>Tutar</p>
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })<!--Miktar*fiyat-->

    <!--Burada otomatik olarak ID çekme işlemi yapılacak-->

    <br />

    <button class="btn btn-success">Kaydet</button>

</form>
<!--ürünlere fancybox eklenecek-->